### ISSUE TITLE
Lightning Gallery - engineering review [LAI-dalle-mini-poster-App]

### ISSUE THREAD

**Issue by manskx** [Lightning-AI/LAI-dalle-mini-poster-App#5]
Thanks for submitting your component to Lightning Gallary.

Looks good. Here is some feedback regarding LAI-dalle-mini-poster-App in order to get accepted in the Lightning Gallery.

1- This repo is not a template, so the readme is not accurate `Click on the "Use this template"`

2- maybe naming it `lightning install app lightning/dalle_mini_poster` ? cc: @zippeurfou 

3- Could you update the setup.py to include correct details about the app package.

4- I ran into issues while running the app, seems related to: https://github.com/Lightning-AI/LAI-research-template-App/issues/89

```
Your Lightning App is starting. This won't take long.
2022-07-27 13:42:46.098 | DEBUG    | research_app.components.model_demo:__init__:38 - OUTPUT_IMAGES=1
[NbConvertApp] Converting notebook resources/DALL·E_mini_Inference_pipeline.ipynb to html
[NbConvertApp] Writing 1137454 bytes to /var/folders/2p/23s0sh_s7ys41qy4fln80hwh0000gn/T/tmp5l_ixcva/index.html
ERROR: Found an exception when loading your application from app.py. Please, resolve it to run your app.

Traceback (most recent call last):
  File "app.py", line 144, in <module>
    app = L.LightningApp(
  File "/Users/mansy/src/lightning/src/lightning_app/core/app.py", line 107, in __init__
    self._update_layout()
  File "/Users/mansy/src/lightning/src/lightning_app/core/app.py", line 424, in _update_layout
    layout = _collect_layout(self, component)
  File "/Users/mansy/src/lightning/src/lightning_app/utilities/layout.py", line 30, in _collect_layout
    layout = flow.configure_layout()
  File "app.py", line 27, in configure_layout
    return frontend.web.StaticWebFrontend(serve_dir=self.serve_dir)
AttributeError: module 'lightning.app.frontend' has no attribute 'web'

```

5- Please make sure that the CI is green :))

6- Nice to have: use lightning components from the gallery e.g. instead of adding your own [JupyterLab](https://github.com/Lightning-AI/LAI-dalle-mini-poster-App/blob/main/research_app/components/jupyter_notebook.py) component, you could use [Jupyter Notebook](https://lightning.ai/component/cRH1UHnvBx-Jupyter%20Notebook)

If you have any questions, please reach out! we will be happy to assist you to land your component to the Lightning gallery.

cc: @aniketmaurya @zippeurfou

**Comment by aniketmaurya** [comment]
hi @manskx, I have addressed the issues mentioned in this [PR](https://github.com/Lightning-AI/LAI-dalle-mini-poster-App/pull/7)

**Comment by manskx** [comment]
Thanks @aniketmaurya, it looks great 🚀
